# SPDX-License-Identifier: BSD-3-Clause
# x2_interp test: 2x upsample + 32-tap float32 RRC FIR applied to complex float16.

KERNEL = x2_interp
SRCS   = test_x2_interp.c x2_interp.c

include ../../common/kernel.mk
